### PR TITLE
GERONIMO-6805: Use a time SPI abstraction to provide time to the transaction manager

### PR DESCRIPTION
**Pull request by efge**

### CODE REVIEW

**Review by rmannibucau — APPROVED** [review]
Works for me.
Just a side question not very important: do you want to add a SettableTimeProvider in main jar (next to System one) to ease the usage of such a feature? not blocking anyway.

**Comment by efge** [comment]
Given the triviality of the implementation for those that need it (a simple lambda for those on Java >= 8) I felt it was not really needed in the base project.

**Comment by rmannibucau** [comment]
@efge depends how you use it I guess. The normal case will be that you don't instantiate yourself the tx mgr (spring, tomee, .... will do) so you can inject a custom provider and then you need to cast this provider to "set" the time value you want (I assume more than a delta). In such a case it makes sense to have a built in impl use can just configure in tomee.xml or so - but it can also go in tomee integration layer, this is why I put a "?" on it.

**Comment by efge** [comment]
@rmannibucau you know more than me about the various environments in which this may be used so I defer to you on what's more convenient and practical.

**Comment by rmannibucau** [comment]
@jeanouii / @jgallimore any opinion on this one? Do you want to follow up on this PR (on the project itself it is ready to merge IMHO, just want to ensure we don't miss some ecosystem integration, in particular when so easy to get.

edit: let's wait ~one more week to see if we get feedback otherwise we will integrate it as it (it is holidays there atm so can delay reviews)

**Comment by efge** [comment]
Ping?

**Comment by efge** [comment]
Hi. Is there anything more I should do before this can be merged?

**Comment by jgallimore** [comment]
It looks ok - I'll run some tests with this change this afternoon.

**Comment by rzo1** [comment]
@jgallimore any results from the tests? :)

**Comment by jgallimore** [comment]
This looks good to me.

**Review by jgallimore — APPROVED** [review]

**Comment by efge** [comment]
Could someone have a look at merging this, if it's ok?

**Comment by fpapon** [comment]
@efge thank you for your contribution! I would like to merge but is it possible for you to squash the commits?

**Comment by efge** [comment]
@fpapon done, but note that I'm not working on this anymore at the moment

**Comment by fpapon** [comment]
@efge thank you! No problem, we will include this in the next release for the community :)

**Pull request merged**
