### PR TITLE
Use Clock (DRAFT)

### PR DESCRIPTION
**Pull request by efge**
Example of what can be done by using a `Clock` to manage time.

### CODE REVIEW

**Comment by rmannibucau** [comment]
Hi @efge , I know it is a draft but as written on the mailing list, it should be a TimeMsProvider SPI you can set on the tx mgr and not a clock hardcoded impl because it is slower on some OS. Otherwise +1.

**Comment by efge** [comment]
Hi @rmannibucau. I understand the request, but `Clock` *is already* a time provider interface, and the only method we'll use, `Clock.millis()`, can be implemented as fast as needed by someone having the requirements.

**Comment by rmannibucau** [comment]
@efge yes and no. The main issue is clock as an API requires 6 methods to be implemented whereas we just need one to evaluate current time (in ms) so I'd use a CurrentTimeMsProvider {now()} interface + SystemCurrentImpl {} + ClockImpl {ClockImpl(Clock)}. Default would be SystemCurrentImpl and you can configure it to use clock one if needed - but note that once you have this interface you just implement a lambda instead of implementing a Clock which is way simpler for testing with is your use case, right?

**Comment by efge** [comment]
@rmannibucau as you wish, I can do that.

**Comment by efge** [comment]
See #6

**Pull request closed without merging**
